---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    ports:
      - '29092:29092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    extra_hosts:
      - "moby:127.0.0.1"
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 9081:9081
    depends_on:
      - kafka
    environment:
      - SERVER_PORT=9081
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:32181
      - KAFKA_CLUSTERS_0_NAME=local
  kafka-setup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    hostname: kafka-setup
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                       cub kafka-ready -b kafka:29092 1 60 && \
                       kafka-topics --create --if-not-exists --topic atm-movements --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 && \
                       kafka-topics --create --if-not-exists --topic online-movements --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 && \
                       kafka-topics --create --if-not-exists --topic merchant-movements --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 && \
                       kafka-topics --create --if-not-exists --topic datagen-fraudsimulator-data-results --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 && \
                       kafka-topics --create --if-not-exists --topic datagen-fraudsimulator-data --bootstrap-server kafka:29092 --partitions 1 --replication-factor 1 && \
                       sleep infinity'"
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    extra_hosts:
      - "moby:127.0.0.1"
  fraud-simulator:
    image: fraud-simulator:1.0.0-SNAPSHOT
    ports:
      - 8090:8090
    depends_on:
      - kafka
      - kafka-setup
    environment:
      - QUARKUS_HTTP_PORT=8090
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
